improved config log message in the case an image is missing
Test config
```
switch01:
  kind: linux
  runtime: ignite
  image: networkop/cx:5.0.1
  memory: 768MB
```

Before:
```
Error: missing required image for node "switch01"
```

After:
```
Error: missing required "kernel" image for node "switch01"
```

Similar output is generated when the `sandbox` images is
missing, when using the ignite runtime.